Create CONTRIBUTING.md
dataframehq/whale pull request #61
Opened 2020-10-25 17:53 UTC by Victoriapm

Closes #56 

I've added the basic guidelines on how to contribute trough PR's, work on existing issues or new ones. 
Let me know what you think!

2020-10-25 19:26 UTC, biomunky commented on CONTRIBUTING.md
> +5. Go to GIthub and make a pull request, please include all the information possible.
GIthub -> Github

2020-10-26 05:35 UTC, rsyi requested changes
Thanks for taking a stab at this, @Victoriapm! This looks great. Added a few nits (and biomunky added one as well), but will merge once these are changed. :)

2020-10-26 05:35 UTC, rsyi commented on CONTRIBUTING.md
> +## General Instructions
nit: can you un-capitalize "Instructions" (let's use a consistent format for all the titles)

2020-10-26 05:35 UTC, rsyi commented on CONTRIBUTING.md
> +3. Add your files on the new branch
nit: period at the end of the sentence

2020-10-26 05:35 UTC, rsyi commented on CONTRIBUTING.md
> +4. Commit locally and push to the new branch with ``git push -u origin feature_name``
nit: period

2020-10-26 05:35 UTC, rsyi commented on CONTRIBUTING.md
> +## Working on Existent Issues
same here: "Working on existent issues"

2020-10-26 05:35 UTC, rsyi commented on CONTRIBUTING.md
> +## Working on New Issues
same here: "Working on new issues"

2020-10-27 18:33 UTC, rsyi commented
Hey @Victoriapm -- actually going to just go ahead and merge this. Don't worry about the nits. Have some other edits to make, so I'll make them :)

2020-10-27 18:33 UTC, rsyi approved these changes

2020-10-27 18:33 UTC, merged

2020-10-27 18:39 UTC, Victoriapm commented
Great, thanks! 
Sorry for the delay, was planning to do it tonight.